# An Introduction to numpy

**Requirements**: in order to execute this notebook, you will need the following packages:

1. numpy 
2. matpoltlib

You can install them by running: `pip intall --user numpy matplotlib` in your terminal.

Now we can import them, using `np` and `plt` as shorthands for `numpy` and `matplotlib.pyplot` respectively.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Okay, so what is numpy?

numpy ([website](https://numpy.org/)) brands itself as "The fundamental package for scientific computing with Python". What's it good for?

1. **Arrays**: you want to use numpy every time you are dealing with numerical lists, matrices, and higher dimensional arrays. Looping over entries with 'for' loops just isn't as quick or readable as numpy's powerful vectorization, indexing, and broadcasting.

2. **Mathematical functions**: it also includes comprehensive mathematical functions, random number generators, linear algebra, transforms, and more.

# Let's see some code

## Arrays
Define `mylist` as a normal python list, and `myarray` as a numpy array, with identical contents.

In [9]:
mylist = [0,1,2,3,4,5]
myarray = np.array([0,1,2,3,4,5])
print(mylist)
print(myarray)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


They look identical! Why is this different from normal lists?

numpy arrays support a lot of array operations, which don't work with lists.

In [17]:
print(myarray + 5)            # add 5 to every element in the list
print(myarray + myarray)      # add two lists together, element by element
print(myarray * myarray)      # multiply two lists together, element by element

[ 5  6  7  8  9 10]
[ 0  2  4  6  8 10]
[ 0  1  4  9 16 25]


These operations don't work for normal lists, the following code snippet uses a `try-except` block to demonstrate this: the code under `try` will execute, but if it encounters any error, it won't crash everything, but simply execute the code under `except`.

In [ ]:
try: 
    print(mylist * mylist)
except Exception as e:
    print(e)
    print("numpy arrays are different from lists!")

We can extend these arrays to many dimensions

In [23]:
mymatrix = np.array([[[0,1,2],[3,4,5]], [[6,7,8],[9,10,11]], [[12,13,14], [15,16,17]]])
print(mymatrix)
print(mymatrix.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
(3, 2, 3)


Indexing works pretty much the same way as lists. However, note that you can use lists to index numpy arrays.

In [40]:
mylist = [0,1,2,3,4]
myarray = np.array(mylist)
print(myarray[0])
print(myarray[1:3])
print(myarray[[True, False, False, False, True]])
print(myarray[[-1,3,2]])

0
[1 2]
[0 4]
[4 3 2]


## Vectorization, indexing, broadcasting, etc.

This is the real power of numpy arrays. Let's see some examples

Let's say I want to select all positive entries in a list of numbers. This is how you would've done it in the good old days.

In [24]:
mylist = [0,-1,2,-3,4,-5,6]             # some list we want to get all positive numbers from
pos = []                                # new list to append positive numbers to
for number in mylist:
    if number > 0:
        pos.append(number)
print(pos)

[2, 4, 6]


Once you start writing more complex code, for loops like these become slow, and hard to read. Let's see how numpy fixes this.

In [26]:
myarray = np.array(mylist)              # some list we want to get all positive numbers from
pos = myarray[myarray > 0]
print(pos)

[2 4 6]


Very nice! How did it work? Let's see some details.

When we print `myarray > 0` we see that it returns an array of booleans, stating whether the **expression** that we have just written (myarray > 0) is True or False, at each index of the array.

In [31]:
expr = myarray > 0
print(expr)

[False False  True False  True False  True]


We can then use this array to index our original numpy array

In [33]:
print(myarray[expr])

[2 4 6]


We can now build more complicated expressions, but the idea is the same.

In [42]:
myarray = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(myarray[ (myarray%2==0) & (myarray>5) ])    # select all even numbers greater than 5

[ 6  8 10]


## Some useful functions

I won't even get close to scratching the surface of all the math functions that numpy provides for us. numpy has a good [user's guide and tutorials](https://numpy.org/doc/stable/user/whatisnumpy.html), that you should check out after you're done with this notebook.

Initializing new arrays:

In [58]:
myarray = np.arange(0,10,1)                  # initialize arrays with all integers from 0 to 9
print(myarray)
myarray = np.arange(0,10,0.5)                # initialize arrays with all half integers from 0 to 9.5
print(myarray)
mymatrix = np.random.random((3,3))           # random [0,1] 3x3 matrix
print(mymatrix)
myarray = np.logspace(0,3,4)                 # logarithmic space
print(myarray)

[0 1 2 3 4 5 6 7 8 9]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[[0.94732123 0.18025672 0.11336971]
 [0.59348573 0.69768466 0.14787952]
 [0.31788316 0.69607598 0.99209459]]
[   1.   10.  100. 1000.]


Simple functions:

In [66]:
mymatrix = np.random.random((3,3))
print(np.exp(mymatrix))                # exponentiate every entry
print(np.log(mymatrix))                # take log of every entry
print(mymatrix.sum())                  # sum all entries
print(mymatrix.max())                  # get max of all entries
print(mymatrix.min())                  # get min of all entries

[[2.60752952 1.76955569 2.35279975]
 [1.89576584 1.46074149 1.49524997]
 [2.71598705 1.83965509 2.70215557]]
[[-4.24866834e-02 -5.60841682e-01 -1.55945286e-01]
 [-4.46876501e-01 -9.70366381e-01 -9.10573620e-01]
 [-8.44915125e-04 -4.94988192e-01 -5.96795982e-03]]
6.408381545418203
0.9991554417148625
0.37894417483476783


## Joining arrays

Simple concatenation

In [71]:
myarray1 = np.arange(0,5,1)
myarray2 = np.arange(5,10,1)
print(myarray1, myarray2)
print(np.concatenate((myarray1, myarray2), axis=0))

[0 1 2 3 4] [5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


Stacking two arrays on top of each other

In [74]:
myarray1 = np.arange(0,5,1)
myarray2 = np.arange(5,10,1)
print(myarray1, myarray2)
print(np.vstack((myarray1, myarray2)))

[0 1 2 3 4] [5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


Here is another way to do it

In [90]:
myarray1 = np.arange(0,5,1)
myarray2 = np.arange(5,10,1)
print("Original arrays", myarray1, myarray2)

myarray1_new = np.expand_dims(myarray1, axis=0)
myarray2_new = np.expand_dims(myarray2, axis=0)
print("Expanded arrays", myarray1_new, myarray2_new)

mymatrix = np.concatenate((myarray1_new, myarray2_new), axis=0)
print("Resulting matrix", mymatrix)
print("transposed", mymatrix.T)

Original arrays [0 1 2 3 4] [5 6 7 8 9]
Expanded arrays [[0 1 2 3 4]] [[5 6 7 8 9]]
Resulting matrix [[0 1 2 3 4]
 [5 6 7 8 9]]
transposed [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
